from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ── Chat request schema (shared across routes) ──────────────


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=10000)
    image_url: Optional[str] = Field(None, description="Base64-encoded image data URL (data:image/...;base64,...)")


# ── Citation schemas ───────────────────────────────────────


class Citation(BaseModel):
    """A single citation marker with source information."""

    marker: str  # e.g. "[1]", "[2]"
    document_id: int
    filename: str
    page_number: Optional[int] = None
    chunk_id: int
    snippet: str


# ── Document schemas ───────────────────────────────────────


class DocumentResponse(BaseModel):
    id: int
    session_id: int
    filename: str
    content_type: Optional[str] = None
    file_size: Optional[int] = None
    status: str  # processing, ready, failed
    chunk_count: int
    error_message: Optional[str] = None
    created_at: datetime

    model_config = {"from_attributes": True}


class DocumentListResponse(BaseModel):
    documents: List[DocumentResponse]


class UploadResponse(BaseModel):
    document: DocumentResponse
    message: str


# ── Updated ChatResponse with citations ────────────────────


class MessageResponse(BaseModel):
    id: int
    session_id: int
    role: str
    content: str
    image_url: Optional[str] = None  # Base64-encoded image data URL for multimodal messages
    citations: Optional[str] = None  # JSON-serialized citation list
    confidence: Optional[int] = None  # F6 Cap 2: 0-100 advisory score
    confidence_reason: Optional[str] = None  # F6 Cap 2: one-line why
    created_at: datetime

    model_config = {"from_attributes": True}


class MemoryExtractionStatus(BaseModel):
    """
    Outcome of the automatic memory extraction step.

    Fields:
        saved:      Whether a memory was actually persisted.
        memory_id:  The database ID of the saved memory (None if nothing saved).
        reason:     Coded reason string (e.g. "saved", "nothing_to_save",
                    "ollama_unavailable", "disabled", "sensitive_input").
        content:    The extracted memory content (None if nothing extracted).
        category:   The extracted memory category (None if nothing extracted).
    """
    saved: bool = False
    memory_id: Optional[int] = None
    reason: str = "nothing_to_save"
    content: Optional[str] = None
    category: Optional[str] = None


class ChatResponse(BaseModel):
    user_message: MessageResponse
    assistant_message: MessageResponse
    citations: List[Citation] = Field(default_factory=list)
    sources_used: bool = False  # Whether retrieved documents were included
    memories_used: bool = False  # Whether saved memories were included
    memory_extraction: Optional[MemoryExtractionStatus] = None  # Memory extraction outcome


class TerminalApprovalResponse(BaseModel):
    """Response when the agent proposes a command and asks for approval."""
    type: str = "terminal_approval"  # Discriminator for frontend
    pending_command: str  # The command the agent wants to run
    approval_message: str  # Full message shown to the user
    session_id: int


# ── SSE event schemas (Phase 5A streaming) ─────────────────


class SSEStartEvent(BaseModel):
    """Event sent when a streaming session begins."""
    session_id: int
    sources_used: bool = False
    memories_used: bool = False


class SSETokenEvent(BaseModel):
    """Event sent for each token generated by Ollama."""
    token: str


class SSECompleteEvent(BaseModel):
    """Event sent when streaming finishes successfully."""
    message_id: int
    citations: List[Dict[str, Any]] = Field(default_factory=list)
    sources_used: bool = False
    memories_used: bool = False


class SSEErrorEvent(BaseModel):
    """Event sent when an error occurs during streaming."""
    code: str  # e.g. "OLLAMA_ERROR", "SESSION_NOT_FOUND", "INTERNAL_ERROR"
    detail: str


class SSECancelledEvent(BaseModel):
    """Event sent when the client disconnects during streaming."""
    detail: str = "Generation cancelled by client"


# ── Search schemas (Phase 5C) ──────────────────────────────


class SearchResult(BaseModel):
    """A single search result from the conversation search endpoint."""
    session_id: int
    session_title: str
    message_id: int
    role: str
    content: str
    snippet: str  # First 150 chars
    created_at: datetime
